# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    encoders:
         FOS\UserBundle\Model\UserInterface: bcrypt
         Symfony\Component\Security\Core\User\User:
             algorithm: bcrypt
             cost: 12
    role_hierarchy:
        ROLE_BUREAU:      ROLE_USER
        ROLE_ADMIN:       ROLE_BUREAU
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            #anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

            logout:       true
            anonymous:    true

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/club/[0-9]+/status$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/stripe/(live|test)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
